apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: factorizator
  namespace: factorizator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: factorizator
  minReplicas: 1
  maxReplicas: 200
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleDown:
        stabilizationWindowSeconds: 30
    
